### ISSUE TITLE
please add to bower

### ISSUE THREAD

**Issue by psnell** [bishopZ/Typecast.js#28]

**Comment by seth2810** [comment]
I'll make bower and npm configurations in #29, and temporary register my fork as package in bower and npm as 'typecast-js'. I'll unregister my packages after pull request was been accepted.

**Comment by seth2810** [comment]
please close this issue, because it's done.

**Comment by bishopZ** [comment]
Yes, thank you again. I would have done myself, but do not have time just now. Looking forward to v0.3!
